#!/bin/bash
# Excalidraw Canvas — First-time Setup
# Run this once after cloning the repo

echo "============================================"
echo "  Excalidraw Canvas — Setup"
echo "============================================"
echo ""

# Check Node.js
if ! command -v node &> /dev/null; then
  echo "❌ Node.js not found. Install from https://nodejs.org"
  exit 1
fi
echo "✅ Node.js $(node -v)"

# Check npm
if ! command -v npm &> /dev/null; then
  echo "❌ npm not found."
  exit 1
fi
echo "✅ npm $(npm -v)"

# Ask for canvas files path
echo ""
echo "Where should Excalidraw save canvas files?"
echo "This folder will store .excalidraw files, backups, and file ordering."
echo ""
read -p "Canvas files path: " CANVAS_PATH

if [ -z "$CANVAS_PATH" ]; then
  echo "❌ Path cannot be empty."
  exit 1
fi

# Create directory if it doesn't exist
mkdir -p "$CANVAS_PATH"
if [ ! -d "$CANVAS_PATH" ]; then
  echo "❌ Could not create directory: $CANVAS_PATH"
  exit 1
fi
echo "✅ Canvas directory: $CANVAS_PATH"

# Create _backups subdirectory
mkdir -p "$CANVAS_PATH/_backups"
echo "✅ Backup directory: $CANVAS_PATH/_backups"

# Ask for port
echo ""
read -p "Server port (default 4000): " PORT
PORT=${PORT:-4000}
echo "✅ Port: $PORT"

# Write .env file
cat > .env << EOF
# Excalidraw Canvas — Generated by setup.sh on $(date)
CANVAS_DIR=$CANVAS_PATH
PORT=$PORT
EOF
echo "✅ .env file created"

# Install dependencies
echo ""
echo "Installing dependencies..."
npm install
echo "✅ Dependencies installed"

# Build MCP (if mcp folder exists alongside)
if [ -d "../mcp" ]; then
  echo ""
  echo "Building MCP server..."
  cd ../mcp && npm install && npx tsc && cd ../Main\ Code
  echo "✅ MCP built"
fi

echo ""
echo "============================================"
echo "  Setup Complete!"
echo "============================================"
echo ""
echo "  Canvas files: $CANVAS_PATH"
echo "  Server port:  $PORT"
echo ""
echo "  Start the app:"
echo "    npm run dev          (Vite frontend on :5173)"
echo "    npx tsx server/index.ts  (API server on :$PORT)"
echo ""
echo "  Or use the Start-Excalidraw script."
echo "============================================"
